### PR TITLE
Problem: examples and docs are not packaged

### PR DESCRIPTION
**Pull request by bluca**
Solution: see commits

### CODE REVIEW

**Comment by bluca** [comment]
@hintjens - in order to enable auto-build on OBS on merge/commit/push, the hook on Github has to be created:

https://github.com/imatix/gsl/settings/hooks/new?service=obs

I can either take care of it for you if you give me access to this repo, or give you access to home:zeromq if you create an account on https://build.opensuse.org

**Comment by bluca** [comment]
@hintjens @evoskuil - what do we do for the triggers?

**Comment by evoskuil** [comment]
@bluca sorry, I missed this. I don't understand the question.

**Comment by bluca** [comment]
No problem!

So we have set up automated package builds and publish on OBS, that get triggered by every merge: https://build.opensuse.org/project/show/home:zeromq:git-stable

If I create a token for you, could you please set up the service in this repository and add it?

**Comment by evoskuil** [comment]
Yes, hopefully :)

**Comment by bluca** [comment]
@evoskuil - I've sent a PGP encrypted mail with the token and also instructions for setup

**Comment by bluca** [comment]
@hintjens - we need someone with admin rights, do you have time to help? It just takes a couple minutes

**Pull request merged**
