### PR TITLE
Problems: various packaging problems

### PR DESCRIPTION
**Pull request by bluca**
Solutions: see commits

### CODE REVIEW

**Comment by jimklimov** [comment]
LGTM. Just in case, is Imatix still in business as an entity, or should copyrights be assigned to "community members" or some such?

**Comment by bluca** [comment]
A question for @evoskuil

**Comment by evoskuil** [comment]
@hintjens was iMatix CEO and there is no new information on the [website](http://www.imatix.com). New work not controlled by this project's GPL3 license is the property of its creators and can be assigned however they see fit. Something like "GSL Developers" seems fine and is what we do in Libbitcoin.

**Comment by bluca** [comment]
I've added a new line with "GSL Developers" and changed the maintainer field and email address to the zmq mailing list

**Pull request merged**
